#!/bin/bash
clear

# Code für Delete_User von Kevin Köhn

function deluser(){
  echo -n "| Geben Sie den User ein: "
  read USER
  if [[ `grep ^${USER}: /etc/passwd ` ]]; then
    echo "|  dieser User existiert!"
    echo -n "|  Wollen Sie das Heimatverzeichnis auch Löschen? [J/n]"
    read OK
    if (( "$OK" == "n" )) || (( "$OK" == "N" )); then
      echo "userdel $USER"
    else
      echo "userdel -r $USER"
    fi
  else 
    echo "| dieser User existiert nicht!"
    echo "| Das Programm wird beendet!" 
    exit 3
  fi
  exit 0
}

